import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, doc, setDoc, getDoc, arrayUnion } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const app = initializeApp(firebaseConfig); const auth = getAuth(app); const db = getFirestore(app);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,saved:new Set(),chart:null,topic:null};

const grades=[
 {id:9,title:'Lớp 9',desc:'Điện học • điện từ • quang học • năng lượng',topics:['Định luật Ôm','Công suất điện','Điện từ','Quang học']},
 {id:10,title:'Lớp 10',desc:'Cơ học nền tảng • động lực học • năng lượng',topics:['Chuyển động','Newton','Công & năng lượng','Động lượng']},
 {id:11,title:'Lớp 11',desc:'TRỌNG TÂM • điện, dao động, sóng, nhiệt',topics:['Dao động','Sóng cơ','Điện trường','Dòng điện']},
 {id:12,title:'Lớp 12',desc:'Điện xoay chiều • quang • hạt nhân • lượng tử',topics:['AC RLC','Quang học','Lượng tử','Hạt nhân']}
];
const topics={
'9':[
topic('Định luật Ôm','Cường độ dòng điện qua đoạn mạch tỉ lệ thuận với hiệu điện thế hai đầu đoạn mạch và tỉ lệ nghịch với điện trở.','I=\\frac{U}{R}','U: V; I: A; R: Ω','Mô hình đoạn mạch Ohm, nhiệt độ và các yếu tố vật lý của dây được coi ổn định.','U tăng 2 lần, R không đổi → I tăng 2 lần.',['Tìm I/U/R','Đoạn mạch','Định luật Ôm']),
topic('Đoạn mạch nối tiếp','Các phần tử mắc nối tiếp có cùng cường độ dòng điện; hiệu điện thế toàn mạch bằng tổng hiệu điện thế thành phần.','R_{td}=R_1+R_2+\cdots','R: Ω','Chỉ dùng cho cấu trúc nối tiếp.','Điện trở tương đương luôn lớn hơn từng điện trở thành phần.',['Tính Rtd','Chia U','Công suất từng điện trở']),
topic('Đoạn mạch song song','Các nhánh có cùng hiệu điện thế; dòng điện toàn mạch là tổng dòng điện qua các nhánh.','\frac1{R_{td}}=\frac1{R_1}+\frac1{R_2}+\cdots','R: Ω','Dùng khi các nhánh chung hai nút.','Với hai điện trở: Rtd=R1R2/(R1+R2), nhỏ hơn điện trở nhỏ nhất.',['Tính Rtd','Chia I','Mạch hỗn hợp']),
topic('Công suất điện','Tốc độ tiêu thụ điện năng của thiết bị.','P=UI=I^2R=\frac{U^2}{R}','P: W','Chọn dạng theo dữ kiện đã biết.','P là tốc độ dùng năng lượng, không phải tổng điện năng.',['Công suất','Điện năng','Tiền điện'])],
'10':[
topic('Tốc độ','Độ nhanh chậm của chuyển động được mô tả bằng quãng đường đi được trong một đơn vị thời gian.','v=\frac{s}{t}','v: m/s; s: m; t: s','Chuyển động thẳng đều dùng trực tiếp; trường hợp biến đổi cần xét vận tốc tức thời/trung bình.','Đổi km/h ↔ m/s: chia hoặc nhân 3,6.',['Đổi đơn vị','Tốc độ trung bình','Đồ thị s-t']),
topic('Gia tốc','Gia tốc mô tả mức độ thay đổi của vận tốc theo thời gian.','a=\frac{\Delta v}{\Delta t}','m/s²','Với chuyển động biến đổi đều, a không đổi.','a có hướng; không được chỉ nhìn độ lớn rồi bỏ qua chiều.',['Chuyển động biến đổi đều','Đồ thị v-t','Tìm quãng đường']),
topic('Định luật II Newton','Hợp lực quyết định gia tốc của hệ vật.','\vec F_{hl}=m\vec a','F: N; m: kg; a: m/s²','Phải xác định hệ và vẽ tất cả lực trước khi chiếu trục.','Nếu cùng lực tác dụng, m tăng 2 lần → a giảm 2 lần.',['Mặt phẳng nghiêng','Ma sát','Hệ vật']),
topic('Công của lực','Công đo năng lượng lực truyền cho vật qua chuyển dời.','A=Fs\cos\alpha','J','F và s là độ lớn; α là góc giữa lực và chuyển dời.','Lực vuông góc chuyển dời → công bằng 0.',['Công tổng','Động năng','Công ma sát']),
topic('Động lượng','Động lượng đặc trưng cho trạng thái chuyển động và là đại lượng vectơ.','\vec p=m\vec v','kg·m/s','Chọn hệ quy chiếu và chiều dương rõ ràng.','Trong hệ kín, tổng động lượng được bảo toàn.',['Va chạm','Bảo toàn động lượng','Phản lực'])],
'11':[
topic('Dao động điều hòa','Li độ biến thiên theo hàm sin/cos; gia tốc luôn hướng về vị trí cân bằng.','x=A\cos(\omega t+\varphi)','x,A: m; ω: rad/s; t: s','A>0, ω>0; pha phụ thuộc trạng thái ban đầu.','a=-ω²x là dấu hiệu bản chất: a luôn kéo vật về O.',['Viết x(t)','Đọc đồ thị x-t','Tìm pha ban đầu','Tìm thời điểm']),
topic('Chu kỳ và tần số','Chu kỳ là thời gian thực hiện một dao động toàn phần; tần số là số dao động trong một giây.','T=\frac1f=\frac{2\pi}{\omega}','T: s; f: Hz; ω: rad/s','Dùng đúng đơn vị và quan hệ nghịch đảo.','f tăng → T giảm.',['Tìm T/f/ω','Đếm dao động','Đồ thị']),
topic('Vận tốc và gia tốc dao động','Vận tốc là đạo hàm của li độ; gia tốc là đạo hàm của vận tốc.','v=-\omega A\sin(\omega t+\varphi),\quad a=-\omega^2x','v: m/s; a: m/s²','Biên: v=0, |a|max; cân bằng: |v|max, a=0.','Có thể dùng v²=ω²(A²-x²) khi không cần xác định dấu v.',['Tìm vmax','Tìm a','Biết x tìm v']),
topic('Năng lượng dao động','Nếu không có ma sát, cơ năng không đổi; động năng và thế năng chuyển hóa qua lại.','W=\frac12kA^2=\frac12m\omega^2A^2','J','Mô hình dao động điều hòa lý tưởng.','Ở biên Wt=W, ở O Wđ=W.',['Tỉ số Wđ/Wt','Tìm A','Thời gian chuyển trạng thái']),
topic('Sóng cơ','Sóng cơ là sự lan truyền dao động trong môi trường vật chất, truyền năng lượng chứ không mang vật chất đi theo một cách tổng thể.','v=\lambda f=\frac{\lambda}{T}','v: m/s; λ: m; f: Hz','Cần môi trường truyền sóng.','λ là khoảng cách giữa hai điểm gần nhau dao động cùng pha.',['Tính λ','Độ lệch pha','Giao thoa']),
topic('Điện trường và cường độ điện trường','Điện trường là môi trường vật lý quanh điện tích; cường độ cho biết lực tác dụng lên một điện tích thử dương.','\vec E=\frac{\vec F}{q}','N/C hoặc V/m','q là điện tích thử dương khi xác định chiều E.','Đường sức điện đi ra từ điện tích dương và đi vào điện tích âm.',['Điện trường điểm','Nguyên lý chồng chất','Công của lực điện']),
topic('Dòng điện không đổi','Dòng điện là dòng chuyển dời có hướng của điện tích; cường độ điện biểu thị lượng điện qua tiết diện mỗi giây.','I=\frac{\Delta q}{\Delta t}','A; q: C; t: s','Quy ước chiều dòng điện là chiều chuyển động của điện tích dương.','Trong kim loại electron chuyển động ngược chiều dòng điện quy ước.',['Tính I/q/t','Nguồn điện','Định luật Ohm']),
topic('Ghép nguồn thành bộ','Nguồn ghép nối tiếp làm tăng suất điện động theo tổng đại số; điện trở trong cũng thay đổi theo cách ghép.','E_b=\sum E_i,\quad r_b=\sum r_i','E: V; r: Ω','Phải xét cực cùng chiều hay ngược chiều.','Nguồn song song giống nhau có E_b=E và r_b=r/n.',['Suất điện động','Hiệu suất nguồn','Mạch ngoài'])],
'12':[
topic('RLC nối tiếp','Tổng trở của R, L, C được tạo bởi thành phần thuần trở và hiệu cảm kháng–dung kháng.','Z=\sqrt{R^2+(Z_L-Z_C)^2}','Ω','Z_L=ωL; Z_C=1/(ωC).','Cộng hưởng khi ZL=ZC → Z=R.',['Cộng hưởng','P, cosφ','Biểu diễn vectơ']),
topic('Công suất điện xoay chiều','Công suất trung bình của mạch AC phụ thuộc điện áp, dòng điện hiệu dụng và hệ số công suất.','P=UI\cos\varphi=I^2R','W','U, I là giá trị hiệu dụng.','Chỉ phần công suất tác dụng trên R thực sự tiêu thụ trung bình.',['cosφ','RLC','Truyền tải điện']),
topic('Sóng điện từ','Điện trường và từ trường biến thiên lan truyền trong không gian, không cần môi trường vật chất.','c=\lambda f','c≈3\times10^8 m/s trong chân không','Trong chân không các sóng điện từ truyền cùng tốc độ.','Tần số càng lớn → bước sóng càng ngắn.',['Phổ điện từ','Bước sóng','Ứng dụng']),
topic('Lượng tử ánh sáng','Ánh sáng trao đổi năng lượng theo từng lượng tử photon có năng lượng phụ thuộc tần số.','E=hf=\frac{hc}{\lambda}','J','h là hằng số Planck.','Photon tần số cao mang năng lượng lớn hơn.',['Quang điện','Photon','Giới hạn quang điện']),
topic('Quang điện ngoài','Electron có thể bật khỏi kim loại nếu photon có năng lượng đủ lớn để thắng công thoát.','hf=A+W_{đ\,max}','J','f≥f0. Với f<f0 thì không xảy ra quang điện ngoài dù tăng cường độ.','Tăng cường độ chủ yếu làm tăng số electron quang điện, không thay thế điều kiện tần số.',['Hiệu điện thế hãm','f0','Công thoát']),
topic('Phóng xạ','Hạt nhân không bền tự biến đổi thành hạt nhân khác và phát bức xạ.','N=N_0 2^{-t/T_{1/2}}','N không có đơn vị; T1/2: s','Quá trình ngẫu nhiên ở từng hạt nhân nhưng tuân quy luật thống kê.','Sau mỗi chu kỳ bán rã, số hạt chưa phân rã còn một nửa.',['Độ phóng xạ','Chu kỳ bán rã','Bảo toàn'])]
};
function topic(name,essence,formula,units,condition,insight,types){return{name,essence,formula,units,condition,insight,types}}
function renderNav(){ $('#navList').innerHTML=`<button class="nav-item active" data-nav="home">⌂ Tổng quan</button>${grades.map(g=>`<button class="nav-item" data-nav="grade" data-grade="${g.id}">▣ ${g.title}</button>`).join('')}<button class="nav-item" data-nav="practice">✓ Luyện tập</button><button class="nav-item" data-nav="saved">★ Đã lưu</button>`; $$('.nav-item').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='home')show('home');if(b.dataset.nav==='grade')showGrade(b.dataset.grade);if(b.dataset.nav==='practice')show('practice');if(b.dataset.nav==='saved')show('saved');closeMenu()})}
function renderGrades(filter=''){const list=grades.filter(g=>(g.title+g.desc+g.topics.join(' ')).toLowerCase().includes(filter.toLowerCase()));$('#gradeGrid').innerHTML=list.map(g=>`<article class="grade-card" tabindex="0" data-grade="${g.id}"><div class="num">${g.id}</div><h3>${g.title}</h3><p>${g.desc}</p><div class="tags">${g.topics.map(x=>`<span class="tag">${x}</span>`).join('')}</div></article>`).join('');$$('.grade-card').forEach(c=>{c.onclick=()=>showGrade(c.dataset.grade);c.onkeydown=e=>{if(e.key==='Enter')showGrade(c.dataset.grade)}})}
function show(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id+'View').classList.add('active');window.scrollTo({top:0,behavior:'smooth'});$$('.nav-item').forEach(x=>x.classList.remove('active'));const n=$(`[data-nav="${id==='home'?'home':id}"]`);if(n)n.classList.add('active');if(id==='saved')renderSaved()}
function showGrade(g){show('detail');const arr=topics[g]||[];const grade=grades.find(x=>x.id==g);$('#detailContent').innerHTML=`<div class="detail-head"><div><span class="eyebrow">${grade.title.toUpperCase()} • CORE</span><h1>${grade.title}: hiểu từ gốc</h1><p class="muted">Mỗi chủ đề đi theo chuỗi: <b>bản chất → công thức → điều kiện → đồ thị → dạng bài.</b></p></div><button class="btn btn-primary" data-action="practiceGrade">Luyện phần này</button></div><div class="topic-grid">${arr.map((t,i)=>`<article class="topic-card"><h3>${t.name}</h3><div class="concept"><b>Bản chất</b><p>${t.essence}</p></div><div class="formula"><small>Công thức lõi</small>\[${t.formula}\]</div><div class="note-grid"><div class="mini"><b>Đơn vị</b>${t.units}</div><div class="mini"><b>Điều kiện</b>${t.condition}</div><div class="mini"><b>Nhớ bản chất</b>${t.insight}</div></div><div class="graph-box"><canvas id="chart-${g}-${i}"></canvas></div><h4>Dạng bài thường gặp</h4><div class="tags">${t.types.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="exercise"><b>Ví dụ nhanh</b><p>${exampleFor(t.name)}</p></div><button class="btn btn-soft save-btn" data-save="${g}-${i}">${state.saved.has(`${g}-${i}`)?'★ Đã lưu':'☆ Lưu chủ đề'}</button></article>`).join('')}</div>`;MathJax.typesetPromise();arr.forEach((t,i)=>drawTopicChart(`chart-${g}-${i}`,t.name));$$('.save-btn').forEach(b=>b.onclick=()=>toggleSave(b.dataset.save));$('[data-action="practiceGrade"]').onclick=()=>show('practice')}
function exampleFor(n){if(n.includes('Dao động'))return 'Một vật có A=5 cm, f=2 Hz. Hãy tìm ω và vmax. Gợi ý: đổi A sang mét, dùng ω=2πf rồi vmax=ωA.';if(n.includes('Vận tốc'))return 'Tại vị trí cân bằng, x=0 nên tốc độ đạt cực đại. Đây là cách đọc bản chất trước khi bấm máy.';if(n.includes('RLC'))return 'Cho R=30Ω, ZL=40Ω, ZC=20Ω. Khi đó Z=√(30²+20²).';if(n.includes('Newton'))return 'Vẽ sơ đồ lực → chọn trục → chiếu định luật II Newton → giải hệ.';return 'Xác định đại lượng cần tìm, kiểm tra đơn vị SI, chọn dạng công thức chứa đúng dữ kiện rồi mới thay số.'}
function drawTopicChart(id,name){const c=document.getElementById(id);if(!c)return;const labels=Array.from({length:81},(_,i)=>(i/20).toFixed(2));let data;if(name.includes('Dao động')||name.includes('Vận tốc'))data=labels.map(x=>Math.cos(Number(x)*2*Math.PI));else if(name.includes('RLC')){data=labels.map(x=>Math.sqrt(1+Math.pow(Math.sin(Number(x)*2*Math.PI),2))*10)}else data=labels.map(x=>Math.sin(Number(x)*2*Math.PI));new Chart(c,{type:'line',data:{labels,datasets:[{data,borderWidth:2,pointRadius:0,tension:.2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{maxTicksLimit:6}},y:{grid:{color:'rgba(148,163,184,.15)'}}}}})}
function renderHomeChart(){const c=$('#heroChart');if(!c)return;const labels=Array.from({length:101},(_,i)=>(i/20).toFixed(2));if(state.chart)state.chart.destroy();state.chart=new Chart(c,{type:'line',data:{labels,datasets:[{data:labels.map(x=>Math.cos(Number(x)*2*Math.PI)),borderWidth:3,pointRadius:0,tension:.25}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{x:{display:false},y:{display:false}}}})}
function toggleSave(id){if(state.saved.has(id))state.saved.delete(id);else state.saved.add(id);persist();showGrade(state.topic||id.split('-')[0]);toast(state.saved.has(id)?'Đã lưu vào bộ nhớ của bạn':'Đã bỏ lưu')}
async function persist(){if(!state.user)return;await setDoc(doc(db,'users',state.user.uid),{saved:[...state.saved],updatedAt:new Date().toISOString()},{merge:true}).catch(()=>{})}
async function loadUserData(){if(!state.user)return;const s=await getDoc(doc(db,'users',state.user.uid)).catch(()=>null);if(s?.exists())state.saved=new Set(s.data().saved||[]);}
function renderSaved(){if(!state.saved.size){$('#savedList').innerHTML='<div class="saved-item"><b>Chưa có chủ đề.</b><p class="muted">Mở một lớp → bấm “Lưu chủ đề”.</p></div>';return}$('#savedList').innerHTML=[...state.saved].map(id=>{const [g,i]=id.split('-'),t=(topics[g]||[])[i];return t?`<div class="saved-item"><b>Lớp ${g} · ${t.name}</b><p>${t.essence}</p><button class="btn btn-soft" onclick="window.__openSaved('${g}')">Mở</button></div>`:''}).join('')}
window.__openSaved=g=>showGrade(g);
const questions=[{q:'Trong dao động điều hòa, tại biên vật có đặc điểm nào?',a:['v=0, |a|max','|v|max, a=0','v và a đều cực đại','x=0'],c:0,e:'Ở biên, x=±A nên v=0; vì a=−ω²x nên độ lớn gia tốc cực đại.'},{q:'Nếu tần số dao động tăng 2 lần thì chu kỳ thay đổi thế nào?',a:['Tăng 2 lần','Giảm 2 lần','Không đổi','Tăng 4 lần'],c:1,e:'T=f⁻¹ nên f tăng 2 lần thì T giảm 2 lần.'},{q:'Trong RLC nối tiếp, cộng hưởng xảy ra khi:',a:['R=0','ZL=ZC','ZL=R','ZC=R'],c:1,e:'Khi ZL=ZC, phần cảm và dung triệt tiêu nhau → Z=R.'}];
function renderQuiz(){const q=questions[Math.floor(Math.random()*questions.length)];$('#quizBox').innerHTML=`<span class="eyebrow">CHECK UNDERSTANDING</span><h2>${q.q}</h2>${q.a.map((x,i)=>`<button class="quiz-option" data-i="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}<p id="quizExplain" class="muted"></p>`;$$('.quiz-option').forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===q.c;$$('.quiz-option').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');$('#quizExplain').textContent=(ok?'✓ Đúng. ':'✗ Chưa đúng. ')+q.e})}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function closeMenu(){$('#sidebar').classList.remove('open');$('#menuBtn').setAttribute('aria-expanded','false')}
$('#menuBtn').onclick=()=>{$('#sidebar').classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',$('#sidebar').classList.contains('open'))};$('#closeMenu').onclick=closeMenu;$('#searchInput').oninput=e=>renderGrades(e.target.value);$('[data-action="start"]').onclick=()=>showGrade('11');$('[data-action="random"]').onclick=()=>showGrade(['9','10','11','12'][Math.floor(Math.random()*4)]);$('[data-action="randomQuestion"]').onclick=renderQuiz);$('[data-action="home"]').onclick=()=>show('home');$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dark',document.body.classList.contains('dark'))};
$('#authBtn').onclick=()=>state.user?signOut(auth):$('#authDialog').showModal();$('#loginBtn').onclick=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('#email').value,$('#password').value);$('#authDialog').close();toast('Đăng nhập thành công')}catch(err){toast(err.code||'Đăng nhập thất bại')}};$('#signupBtn').onclick=async()=>{try{await createUserWithEmailAndPassword(auth,$('#email').value,$('#password').value);$('#authDialog').close();toast('Tạo tài khoản thành công')}catch(err){toast(err.code||'Không tạo được tài khoản')}};
onAuthStateChanged(auth,async u=>{state.user=u;$('#authBtn').textContent=u?'Đăng xuất':'Đăng nhập';await loadUserData();});
renderNav();renderGrades();renderQuiz();renderHomeChart();if(localStorage.getItem('dark')==='true')document.body.classList.add('dark');
