import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, doc, setDoc, getDoc } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const app = initializeApp(firebaseConfig); const auth = getAuth(app); const db = getFirestore(app);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,saved:new Set(),chart:null,topic:null};

const grades=[
{id:9,title:'Lớp 9',desc:'Điện học • công suất • điện năng • từ trường • quang học',topics:['Định luật Ôm','Mạch nối tiếp/song song','Công suất & điện năng','Điện từ','Quang học']},
{id:10,title:'Lớp 10',desc:'Động học • Newton • công • năng lượng • động lượng • chuyển động tròn',topics:['Chuyển động','Newton','Công – năng lượng','Động lượng','Chuyển động tròn']},
{id:11,title:'Lớp 11',desc:'DAO ĐỘNG • SÓNG • ĐIỆN TRƯỜNG • DÒNG ĐIỆN • NHIỆT HỌC',topics:['Dao động điều hòa','Sóng cơ','Điện trường','Dòng điện không đổi','Nhiệt học']},
{id:12,title:'Lớp 12',desc:'Khí lý tưởng • từ trường • AC • quang học • lượng tử • hạt nhân',topics:['Khí lý tưởng','Từ trường','RLC xoay chiều','Sóng điện từ','Lượng tử','Hạt nhân']}
];

const T=(name,essence,formula,units,condition,insight,types,graph='')=>({name,essence,formula,units,condition,insight,types,graph});
const topics={
9:[
T('Định luật Ôm','Dòng điện qua một đoạn mạch phụ thuộc vào hiệu điện thế đặt vào và điện trở cản trở dòng điện.','I=\\frac{U}{R}','I: A; U: V; R: Ω','Đoạn mạch thuần trở, điều kiện vật lý của dây không đổi.','U tăng 2 lần, R giữ nguyên ⇒ I tăng 2 lần.',['Tìm I, U, R','Đoạn mạch','Đo định luật Ôm'],'ohm'),
T('Điện trở dây dẫn','Điện trở phụ thuộc vật liệu, chiều dài và tiết diện dây.','R=\\rho\\frac{l}{S}','ρ: Ω·m; l: m; S: m²','Dùng cho dây dẫn đồng chất, tiết diện đều.','Dây dài hơn ⇒ khó cho dòng đi qua hơn; dây to hơn ⇒ dễ cho dòng đi qua hơn.',['Tính R','Tìm ρ/l/S','So sánh dây']),
T('Nối tiếp','Trong mạch nối tiếp, dòng điện như nhau qua các phần tử; điện áp phân chia.','I=I_1=I_2;\\quad U=U_1+U_2;\\quad R_{td}=R_1+R_2+...','R: Ω; U: V; I: A','Các phần tử nằm trên cùng một nhánh không có nút rẽ.','Rtd luôn lớn hơn từng R thành phần.',['Rtd','Chia điện áp','Công suất']),
T('Song song','Các nhánh song song có cùng hai đầu nên cùng hiệu điện thế; dòng chia theo nhánh.','U=U_1=U_2;\\quad I=I_1+I_2;\\quad \\frac1{R_{td}}=\\sum\\frac1{R_i}','R: Ω','Các nhánh chung hai nút.','Rtd nhỏ hơn điện trở nhỏ nhất.',['Rtd','Chia dòng','Mạch hỗn hợp']),
T('Công suất điện','Cho biết tốc độ thiết bị biến đổi điện năng thành các dạng năng lượng khác.','P=UI=I^2R=\\frac{U^2}{R}','P: W','Chọn công thức theo đại lượng đã biết.','Cùng U: R nhỏ ⇒ P lớn; cùng I: R lớn ⇒ P lớn.',['Tính P','Định mức','So sánh thiết bị']),
T('Điện năng tiêu thụ','Điện năng là năng lượng điện thiết bị đã sử dụng trong khoảng thời gian t.','A=Pt=UIt','A: J; P: W; t: s','Với điện năng thương mại có thể dùng kWh.','1 kWh = 3.6×10^6 J.',['Tính điện năng','Tiền điện','Đổi kWh']),
T('Định luật Jun–Lenxơ','Dòng điện qua điện trở làm dây nóng lên; nhiệt lượng phụ thuộc I, R và thời gian.','Q=I^2Rt','Q: J','Áp dụng cho tác dụng nhiệt của dòng điện.','Tăng I rất mạnh vì Q phụ thuộc I².',['Nhiệt lượng','Bếp điện','Cầu chì']),
T('Hiệu suất sử dụng điện','So sánh năng lượng có ích với năng lượng cung cấp.','H=\\frac{A_{ích}}{A_{toàn}}\\times100\\%','H: %','Năng lượng phải cùng đơn vị.','Hiệu suất không thể lớn hơn 100%.',['Hiệu suất','Động cơ điện','Thiết bị gia dụng']),
T('Từ trường của nam châm','Nam châm tạo ra từ trường; kim nam châm định hướng theo từ trường tại vị trí đặt nó.','\\text{Đường sức từ: ngoài nam châm đi từ N → S}','Không có đơn vị trực tiếp','Mô tả bằng đường sức từ và từ phổ.','Đường sức từ không cắt nhau.',['Nhận biết từ trường','Đường sức','Cực từ']),
T('Lực điện từ','Dòng điện đặt trong từ trường có thể chịu lực điện từ.','F=BIl\\sin\\alpha','F: N; B: T; I: A; l: m','Dây dẫn mang dòng điện đặt trong từ trường.','F cực đại khi dây vuông góc đường sức; F=0 khi song song.',['Xác định chiều lực','Tính F','Động cơ điện']),
T('Cảm ứng điện từ','Từ thông qua mạch biến thiên tạo ra suất điện động cảm ứng.','|\\mathcal E|=\\left|\\frac{\\Delta\\Phi}{\\Delta t}\\right|','E: V; Φ: Wb','Phải có biến thiên từ thông.','Không phải cứ có từ trường là có dòng cảm ứng; phải có biến thiên từ thông.',['Nam châm – cuộn dây','Tìm E','Lenz'])
],
10:[
T('Độ dịch chuyển','Độ dịch chuyển là vectơ nối vị trí đầu và cuối; khác với quãng đường là đại lượng vô hướng.','\\Delta\\vec x=\\vec x_2-\\vec x_1','m','Chọn hệ trục và chiều dương rõ ràng.','Quãng đường có thể lớn hơn độ lớn độ dịch chuyển.',['Đọc trục','Quãng đường vs độ dịch chuyển']),
T('Tốc độ trung bình','Cho biết trung bình vật đi được bao nhiêu quãng đường trong một đơn vị thời gian.','v_{tb}=\\frac{s}{\\Delta t}','m/s','s là tổng quãng đường.','Không được lấy trung bình cộng các tốc độ nếu thời gian đi từng đoạn khác nhau.',['Tốc độ TB','Đổi đơn vị']),
T('Vận tốc trung bình','Là độ dịch chuyển chia thời gian; là đại lượng vectơ.','\\vec v_{tb}=\\frac{\\Delta\\vec x}{\\Delta t}','m/s','Dùng độ dịch chuyển, không dùng tổng quãng đường.','Đi một vòng về điểm cũ ⇒ vận tốc trung bình bằng 0.',['Vận tốc TB','Đồ thị x-t'],'line'),
T('Chuyển động thẳng đều','Vận tốc không đổi cả độ lớn và hướng.','x=x_0+vt;\\quad s=vt','m, s, m/s','a=0.','Đồ thị x–t là đường thẳng; độ dốc chính là v.',['Phương trình x-t','Đồ thị x-t'],'line'),
T('Gia tốc','Gia tốc đo mức độ thay đổi vận tốc theo thời gian.','\\vec a=\\frac{\\Delta\\vec v}{\\Delta t}','m/s²','Với chuyển động biến đổi đều, a không đổi.','Gia tốc có thể ngược chiều vận tốc khi vật đang chậm dần.',['Tính a','Đổi dấu','Đồ thị v-t'],'line'),
T('Chuyển động thẳng biến đổi đều','Vận tốc thay đổi đều theo thời gian.','v=v_0+at;\\quad s=v_0t+\\frac12at^2;\\quad v^2-v_0^2=2as','m; m/s; m/s²','a không đổi.','Đồ thị v–t là đường thẳng; diện tích dưới đồ thị liên quan đến độ dịch chuyển.',['Tìm v','Tìm s','Tìm t'],'parabola'),
T('Định luật I Newton','Nếu hợp lực bằng 0, vật giữ nguyên trạng thái đứng yên hoặc chuyển động thẳng đều.','\\sum\\vec F=0\\Rightarrow\\vec v=\\text{const}','N','Xét trong hệ quy chiếu quán tính.','Không có lực tổng hợp ≠ không có lực; các lực có thể cân bằng nhau.',['Cân bằng lực','Quán tính']),
T('Định luật II Newton','Hợp lực gây ra gia tốc cùng hướng với hợp lực và tỉ lệ nghịch khối lượng.','\\sum\\vec F=m\\vec a','N; kg; m/s²','Phải xét tất cả lực tác dụng lên vật/hệ.','Đây là phương trình động lực học trung tâm.',['Mặt phẳng nghiêng','Ma sát','Kéo vật','Hệ vật']),
T('Trọng lực','Gần mặt đất, vật chịu lực hút của Trái Đất hướng thẳng đứng xuống.','P=mg','N','g≈9.8 m/s² hoặc 10 m/s² tùy đề.','Khối lượng m không đổi nhưng trọng lượng P phụ thuộc g.',['Tính P','Cân bằng']),
T('Lực ma sát trượt','Ma sát trượt cản trở chuyển động tương đối giữa hai bề mặt.','F_{ms}=\\mu N','N','Mô hình ma sát trượt khô.','Ma sát hướng ngược chiều chuyển động tương đối.',['Mặt phẳng ngang','Mặt phẳng nghiêng']),
T('Công của lực','Công đo năng lượng lực truyền qua chuyển dời.','A=Fs\\cos\\alpha','J','α là góc giữa lực và độ dịch chuyển.','α<90°: công dương; α=90°: bằng 0; α>90°: công âm.',['Tính công','Công tổng','Ma sát']),
T('Công suất','Tốc độ thực hiện công.','P=\\frac{A}{t}=Fv\\cos\\alpha','W','Với công suất tức thời dùng vận tốc tức thời.','Hai máy làm cùng công nhưng máy nhanh hơn có công suất lớn hơn.',['Tính P','So sánh máy']),
T('Động năng','Năng lượng vật có do chuyển động.','W_đ=\\frac12mv^2','J','Trong cơ học cổ điển.','Tốc độ tăng 2 lần ⇒ động năng tăng 4 lần.',['Tìm Wđ','Định lý động năng']),
T('Thế năng trọng trường','Năng lượng gắn với vị trí trong trọng trường, phụ thuộc mốc thế năng.','W_t=mgh','J','Chọn mốc h=0.','Giá trị thế năng phụ thuộc mốc nhưng độ biến thiên thế năng mới là đại lượng vật lý quan trọng.',['Tính Wt','Bảo toàn cơ năng']),
T('Cơ năng','Tổng động năng và thế năng của vật.','W=W_đ+W_t','J','Bảo toàn khi chỉ có lực thế thực hiện công.','Khi Wt giảm thì Wđ tăng nếu cơ năng bảo toàn.',['Bảo toàn cơ năng','Rơi tự do']),
T('Động lượng','Đại lượng vectơ đặc trưng cho trạng thái chuyển động.','\\vec p=m\\vec v','kg·m/s','Chọn chiều dương trước khi chiếu.','Khối lượng hoặc vận tốc càng lớn thì độ lớn động lượng càng lớn.',['Va chạm','Nổ','Bảo toàn động lượng']),
T('Xung lượng của lực','Tác dụng của lực trong thời gian Δt làm thay đổi động lượng.','\\vec F\\Delta t=\\Delta\\vec p','N·s','Lực không đổi hoặc dùng lực trung bình phù hợp.','Đổi động lượng càng nhanh ⇒ lực trung bình càng lớn.',['Va chạm','Giảm lực va chạm']),
T('Chuyển động tròn đều','Vật chuyển động trên đường tròn với tốc độ không đổi nhưng vận tốc luôn đổi hướng.','v=\\omega r;\\quad a_{ht}=\\frac{v^2}{r}=\\omega^2r','m/s; rad/s; m/s²','ω không đổi.','Gia tốc hướng tâm luôn hướng vào tâm, dù tốc độ không đổi.',['Tính v','Tính aht','Chu kỳ'],'circle'),
T('Mômen lực','Khả năng làm quay của lực quanh trục phụ thuộc độ lớn lực và cánh tay đòn.','M=Fd','N·m','d là khoảng cách vuông góc từ trục đến giá lực.','Muốn tăng mômen: tăng F hoặc tăng d.',['Đòn bẩy','Cân bằng quay'])
],
11:[
T('Dao động điều hòa – phương trình li độ','Li độ biến thiên tuần hoàn theo sin/cos; vật luôn có xu hướng quay về vị trí cân bằng.','x=A\\cos(\\omega t+\\varphi)','m; rad/s','A>0, ω>0; t tính bằng s.','Pha cho biết trạng thái dao động tại thời điểm xét.',['Viết x(t)','Tìm A, ω, φ','Đọc trạng thái'],'sine'),
T('Chu kỳ – tần số – tần số góc','Chu kỳ là thời gian một dao động; tần số là số dao động mỗi giây.','T=\\frac1f=\\frac{2\\pi}{\\omega};\\quad \\omega=2\\pi f','s; Hz; rad/s','Đổi đúng đơn vị thời gian.','f càng lớn thì T càng nhỏ.',['Tìm T','Tìm f','Tìm ω']),
T('Vận tốc dao động điều hòa','Vận tốc là đạo hàm của x theo t nên lệch pha π/2 so với li độ.','v=-\\omega A\\sin(\\omega t+\\varphi)','m/s','Dao động điều hòa.','Tại biên v=0; tại cân bằng |v| cực đại.',['vmax','Dấu v','Đồ thị v-t'],'sine'),
T('Gia tốc dao động điều hòa','Gia tốc luôn hướng về vị trí cân bằng và tỉ lệ với độ lệch khỏi vị trí cân bằng.','a=-\\omega^2x','m/s²','Dao động điều hòa.','x và a luôn ngược pha.',['amax','Dấu a','Quan hệ a-x'],'line'),
T('Hệ thức độc lập thời gian','Cho phép tìm vận tốc từ vị trí mà không cần biết t.','v^2=\\omega^2(A^2-x^2)','m²/s²','Dao động điều hòa.','Tại |x|=A thì v=0; tại x=0 thì |v|=ωA.',['Tìm v từ x','Tìm A']),
T('Lực kéo về','Hợp lực kéo vật về vị trí cân bằng có độ lớn tỉ lệ với li độ.','F_{kv}=-kx=-m\\omega^2x','N','Dao động của hệ có lực phục hồi tuyến tính.','Dấu “−” thể hiện hướng lực ngược chiều x.',['Tìm lực','Lò xo','Con lắc']),
T('Con lắc lò xo','Chu kỳ phụ thuộc khối lượng và độ cứng lò xo.','T=2\\pi\\sqrt{\\frac{m}{k}};\\quad \\omega=\\sqrt{\\frac{k}{m}}','s; N/m','Dao động nhỏ, lò xo lý tưởng theo mô hình đề.','m tăng ⇒ dao động chậm; k tăng ⇒ dao động nhanh.',['Tính T','Tính k/m','Thay đổi thông số']),
T('Năng lượng dao động điều hòa','Trong mô hình không ma sát, cơ năng không đổi và chuyển hóa giữa động năng và thế năng.','W=\\frac12kA^2=\\frac12m\\omega^2A^2;\\quad W_đ=\\frac12mv^2','J','Bỏ qua ma sát.','Ở biên: Wt=W, Wđ=0; ở O: Wđ=W, Wt=0.',['Bảo toàn cơ năng','Tỉ số năng lượng']),
T('Con lắc đơn','Với dao động nhỏ, con lắc đơn dao động gần điều hòa và chu kỳ phụ thuộc chiều dài, g.','T=2\\pi\\sqrt{\\frac{l}{g}}','s; m; m/s²','Góc lệch nhỏ.','Khối lượng quả nặng không quyết định chu kỳ trong mô hình này.',['Tính T','Tìm l','Tìm g']),
T('Sóng cơ','Sóng là sự lan truyền dao động trong môi trường vật chất, truyền năng lượng chứ không mang vật chất đi theo.','v=\\lambda f=\\frac{\\lambda}{T}','m/s; m; Hz','Cần môi trường truyền sóng.','Tần số do nguồn quyết định; khi đổi môi trường, f của nguồn thường giữ nguyên còn v và λ thay đổi.',['Tính λ','Đổi môi trường','Độ lệch pha'],'sine'),
T('Phương trình sóng','Li độ tại điểm cách nguồn x trễ pha do thời gian truyền sóng.','u=A\\cos(\\omega t-kx+\\varphi);\\quad k=\\frac{2\\pi}{\\lambda}','m; rad/m','Sóng truyền theo chiều +x theo quy ước.','k cho biết tốc độ biến thiên pha theo không gian.',['Viết phương trình','Tìm pha','Tìm λ'],'sine'),
T('Độ lệch pha trong sóng','Hai điểm cách nhau Δx trên phương truyền sóng có độ lệch pha phụ thuộc Δx/λ.','\\Delta\\varphi=\\frac{2\\pi\\Delta x}{\\lambda}','rad','Hai điểm cùng một thời điểm.','Δx=kλ ⇒ cùng pha; Δx=(k+1/2)λ ⇒ ngược pha.',['Cùng pha','Ngược pha','Vuông pha']),
T('Giao thoa sóng – cực đại','Hai nguồn kết hợp tạo vùng tăng cường và triệt tiêu do chồng chất sóng.','\\Delta d=k\\lambda','m','Hai nguồn có cùng tần số và độ lệch pha không đổi.','Cực đại ứng với hai sóng đến cùng pha trong trường hợp nguồn cùng pha.',['Tìm cực đại','Số vân','Khoảng cách']),
T('Giao thoa sóng – cực tiểu','Triệt tiêu xảy ra khi hai sóng đến ngược pha.','\\Delta d=(k+\\frac12)\\lambda','m','Nguồn cùng pha theo mô hình chuẩn.','Đổi điều kiện nguồn có thể làm điều kiện cực đại/cực tiểu thay đổi.',['Tìm cực tiểu','Đếm cực đại']),
T('Sóng dừng – hai đầu cố định','Các điểm nút đứng yên, bụng dao động mạnh; chiều dài dây chứa số nguyên nửa bước sóng.','l=k\\frac{\\lambda}{2};\\quad f_k=k\\frac{v}{2l}','m; Hz','Hai đầu là nút.','Khoảng cách hai nút liên tiếp = λ/2; nút đến bụng gần nhất = λ/4.',['Đếm nút/bụng','Tìm λ','Tìm f'],'standing'),
T('Cường độ điện trường','Cường độ điện trường là lực điện tác dụng lên một đơn vị điện tích dương thử.','\\vec E=\\frac{\\vec F}{q}','N/C = V/m','q thử đủ nhỏ để không làm thay đổi điện trường nguồn.','Chiều E là chiều lực tác dụng lên điện tích dương.',['Điện trường điểm','Chồng chất']),
T('Điện trường của điện tích điểm','Độ lớn điện trường do điện tích điểm giảm theo bình phương khoảng cách.','E=k\\frac{|Q|}{r^2}','N/C','Môi trường đồng nhất; k phụ thuộc môi trường.','r tăng 2 lần ⇒ E giảm 4 lần.',['Tính E','So sánh E','Chồng chất'],'inverse-square'),
T('Công của lực điện','Trong điện trường tĩnh, công của lực điện chỉ phụ thuộc vị trí đầu cuối.','A_{MN}=q(V_M-V_N)','J','Điện trường tĩnh.','Công lực điện không phụ thuộc đường đi.',['Tính A','Hiệu điện thế']),
T('Hiệu điện thế','Hiệu điện thế là công của lực điện khi dịch một đơn vị điện tích dương giữa hai điểm.','U_{MN}=V_M-V_N=\\frac{A_{MN}}{q}','V','q khác 0.','U cho biết mức chênh lệch điện thế, không phải “lượng điện”.',['Tính U','Liên hệ A/q']),
T('Tụ điện – điện dung','Điện dung đặc trưng khả năng tích điện của tụ ở một hiệu điện thế nhất định.','C=\\frac{Q}{U}','F','Tụ điện trong chế độ phù hợp.','C lớn nghĩa là với cùng U, tụ tích được nhiều Q hơn.',['Tính C','Q-U','Năng lượng tụ']),
T('Năng lượng điện trường trong tụ','Năng lượng được tích trữ trong điện trường giữa hai bản tụ.','W=\\frac12CU^2=\\frac{Q^2}{2C}=\\frac12QU','J','Tụ lý tưởng.','Với C cố định, U tăng 2 lần ⇒ W tăng 4 lần.',['Tính W','Ghép tụ']),
T('Dòng điện không đổi','Cường độ dòng điện cho biết điện lượng chuyển qua tiết diện trong một đơn vị thời gian.','I=\\frac{\\Delta q}{\\Delta t}','A; C; s','Dòng điện không đổi: I không đổi theo thời gian.','Trong kim loại, electron chuyển động ngược chiều dòng điện quy ước.',['Tính I','Tính q/t']),
T('Nguồn điện – suất điện động','Nguồn điện duy trì chênh lệch điện thế và biến đổi năng lượng khác thành điện năng.','\\mathcal E=\\frac{A_{ng}}{q}','V','A_ng là công của lực lạ.','Suất điện động không đơn giản là “hiệu điện thế hai cực” trong mọi trạng thái có tải.',['Tính E','Mạch kín']),
T('Định luật Ôm cho toàn mạch','Dòng điện trong mạch kín phụ thuộc suất điện động và tổng điện trở ngoài + trong.','I=\\frac{\\mathcal E}{R+r}','A','Nguồn có suất điện động E và điện trở trong r.','Khi R tăng, I giảm nhưng điện áp mạch ngoài tăng tiến tới E.',['Tính I','Tìm R/r','Hiệu suất']),
T('Hiệu suất nguồn điện','Tỉ số công suất có ích trên mạch ngoài so với công suất do nguồn cung cấp.','H=\\frac{P_{ngoài}}{P_{nguồn}}=\\frac{R}{R+r}\\times100\\%','%','Mạch ngoài thuần trở theo mô hình cơ bản.','R≫r ⇒ nguồn làm việc hiệu quả hơn.',['Tính H','Tìm R/r']),
T('Công suất nguồn','Công suất do nguồn cung cấp cho mạch gồm phần có ích và phần hao phí trên điện trở trong.','P_{nguồn}=\\mathcal EI;\\quad P_{hao}=I^2r;\\quad P_{ngoài}=I^2R','W','Mạch một nguồn cơ bản.','Hao phí tăng mạnh theo I².',['Tính công suất','Tối ưu tải'])
],
12:[
T('Khí lý tưởng – phương trình trạng thái','Mô hình khí lý tưởng bỏ qua tương tác đáng kể giữa các phân tử ngoài va chạm.','pV=nRT=\\frac{m}{M}RT','Pa; m³; mol; K','T phải tính bằng kelvin.','Tăng T ở V không đổi ⇒ p tăng tỉ lệ với T.',['Đổi trạng thái','Tìm p/V/T']),
T('Định luật Boyle','Với lượng khí không đổi và nhiệt độ không đổi, áp suất tỉ lệ nghịch thể tích.','pV=\\text{const}','Pa·m³','n,T không đổi.','p tăng 2 lần ⇒ V giảm 2 lần.',['Đẳng nhiệt','Đồ thị p-V'],'hyperbola'),
T('Định luật Charles','Với lượng khí không đổi và áp suất không đổi, thể tích tỉ lệ thuận nhiệt độ tuyệt đối.','\\frac{V}{T}=\\text{const}','m³/K','n,p không đổi.','Phải dùng T(K), không dùng °C trực tiếp.',['Đẳng áp','Đồ thị V-T'],'line'),
T('Định luật Gay-Lussac','Với lượng khí không đổi và thể tích không đổi, áp suất tỉ lệ thuận nhiệt độ tuyệt đối.','\\frac{p}{T}=\\text{const}','Pa/K','n,V không đổi.','T tính theo K.',['Đẳng tích','Đồ thị p-T'],'line'),
T('Nhiệt lượng','Nhiệt lượng vật nhận/truyền phụ thuộc khối lượng, nhiệt dung riêng và độ biến thiên nhiệt độ.','Q=mc\\Delta T','J','Không có chuyển thể.','ΔT=T2−T1 có thể âm khi vật tỏa nhiệt theo quy ước dấu.',['Tính Q','Cân bằng nhiệt']),
T('Nhiệt nóng chảy riêng','Năng lượng cần để làm nóng chảy hoàn toàn 1 kg chất ở nhiệt độ nóng chảy.','Q=\\lambda m','J/kg','Trong quá trình nóng chảy ở nhiệt độ xác định.','Trong mô hình lý tưởng, nhiệt độ không đổi trong quá trình nóng chảy.',['Chuyển thể','Cân bằng nhiệt']),
T('Nhiệt hóa hơi riêng','Năng lượng cần để hóa hơi hoàn toàn 1 kg chất ở nhiệt độ sôi.','Q=Lm','J/kg','Trong quá trình hóa hơi ở nhiệt độ xác định.','Nhiệt cung cấp dùng phá vỡ liên kết/trạng thái chứ không làm tăng nhiệt độ trong mô hình lý tưởng.',['Hóa hơi','Cân bằng nhiệt']),
T('Công của khí','Khi khí nở chống lại áp suất ngoài, khí thực hiện công.','A=p\\Delta V','J','Áp suất không đổi trong quá trình xét.','Nở: ΔV>0 ⇒ khí thực hiện công dương theo quy ước phổ biến.',['Đồ thị p-V','Công khí'],'pV'),
T('Nội năng – nguyên lý I nhiệt động lực học','Nội năng thay đổi do truyền nhiệt và thực hiện công.','\\Delta U=Q+A','J','A là công tác dụng lên hệ theo quy ước này.','Luôn kiểm tra quy ước dấu công của đề trước khi thay số.',['Nguyên lý I','Đẳng nhiệt','Đẳng áp']),
T('Từ trường – lực Lorentz','Hạt điện tích chuyển động trong từ trường có thể chịu lực vuông góc với vận tốc và từ trường.','F=|q|vB\\sin\\alpha','N; C; m/s; T','Hạt mang điện chuyển động trong từ trường.','Nếu v song song B thì lực bằng 0.',['Tính F','Xác định quỹ đạo']),
T('Lực từ lên dây dẫn','Dòng điện trong dây đặt trong từ trường chịu lực từ.','F=BIl\\sin\\alpha','N; T; A; m','Dây thẳng dài l trong từ trường đều.','Chiều lực xác định bằng quy tắc bàn tay trái theo quy ước chương trình.',['Tính F','Cân bằng']),
T('Từ thông','Từ thông đo mức độ “xuyên qua” một diện tích của từ trường.','\\Phi=BS\\cos\\alpha','Wb','α là góc giữa B và pháp tuyến mặt S.','α=0° ⇒ Φ lớn nhất; α=90° ⇒ Φ=0.',['Tính Φ','Cảm ứng điện từ']),
T('Định luật Faraday–Lenz','Biến thiên từ thông tạo suất điện động cảm ứng; chiều chống lại nguyên nhân gây biến thiên.','\\mathcal E=-\\frac{d\\Phi}{dt}\\approx-\\frac{\\Delta\\Phi}{\\Delta t}','V','Mạch có từ thông biến thiên.','Dấu “−” thể hiện định luật Lenz, không phải chỉ là dấu đại số tùy ý.',['Tính E','Xác định chiều']),
T('Dòng điện xoay chiều hình sin','Điện áp/dòng điện xoay chiều lý tưởng biến thiên tuần hoàn theo sin.','u=U_0\\cos(\\omega t+\\varphi);\\quad i=I_0\\cos(\\omega t+\\varphi_i)','V; A; rad/s','Tín hiệu hình sin.','U0, I0 là biên độ; U, I hiệu dụng không bằng biên độ.',['Viết u/i','Pha','Đồ thị'],'sine'),
T('Giá trị hiệu dụng','Giá trị hiệu dụng của AC là giá trị DC tương đương về tác dụng nhiệt trên điện trở.','U=\\frac{U_0}{\\sqrt2};\\quad I=\\frac{I_0}{\\sqrt2}','V; A','Dạng sin lý tưởng.','Đề cho “220 V AC” thường là giá trị hiệu dụng.',['Đổi U0↔U','Đổi I0↔I']),
T('Cảm kháng','Cuộn cảm cản trở dòng xoay chiều mạnh hơn khi tần số lớn.','Z_L=\\omega L=2\\pi fL','Ω; H; Hz','Cuộn cảm lý tưởng.','f tăng ⇒ ZL tăng.',['Tính ZL','Thay đổi f']),
T('Dung kháng','Tụ điện cản trở AC theo dung kháng, giảm khi tần số tăng.','Z_C=\\frac1{\\omega C}=\\frac1{2\\pi fC}','Ω; F; Hz','Tụ điện lý tưởng.','f tăng ⇒ ZC giảm.',['Tính ZC','Thay đổi f']),
T('Mạch RLC nối tiếp','Tổng trở là độ lớn của tổng thành phần thuần trở và phản kháng.','Z=\\sqrt{R^2+(Z_L-Z_C)^2};\\quad I=\\frac{U}{Z}','Ω; A; V','Nguồn hình sin, RLC nối tiếp.','Không cộng ZL và ZC trực tiếp theo kiểu đại số thông thường; chúng triệt tiêu nhau về pha.',['Tính Z','Tính I','Giản đồ vectơ'],'rlc'),
T('Độ lệch pha RLC','Pha giữa điện áp toàn mạch và dòng điện phụ thuộc hiệu cảm kháng – dung kháng.','\\tan\\varphi=\\frac{Z_L-Z_C}{R};\\quad \\cos\\varphi=\\frac{R}{Z}','rad','RLC nối tiếp.','ZL>ZC: mạch có tính cảm; ZL<ZC: mạch có tính dung.',['Tìm φ','cosφ']),
T('Cộng hưởng điện','Cộng hưởng xảy ra khi cảm kháng bằng dung kháng, làm tổng trở nhỏ nhất đối với RLC nối tiếp.','Z_L=Z_C\\Rightarrow\\omega_0=\\frac1{\\sqrt{LC}};\\quad f_0=\\frac1{2\\pi\\sqrt{LC}}','Hz; rad/s','RLC nối tiếp.','Tại cộng hưởng: Z=R, I cực đại, φ=0, cosφ=1.',['Tìm f0','Tìm L/C','Đồ thị I-f'],'resonance'),
T('Công suất xoay chiều','Công suất trung bình tiêu thụ bởi mạch AC phụ thuộc điện áp, dòng điện hiệu dụng và hệ số công suất.','P=UI\\cos\\varphi=I^2R=\\frac{U^2R}{Z^2}','W','U,I là hiệu dụng.','Chỉ thành phần cùng pha với dòng điện tạo công suất tác dụng trung bình.',['Tính P','cosφ','Bù công suất']),
T('Sóng điện từ','Điện trường và từ trường biến thiên lan truyền cùng nhau; trong chân không không cần môi trường vật chất.','c=\\lambda f=\\frac{\\lambda}{T}','m/s; m; Hz','Trong chân không c≈3×10^8 m/s.','Tần số càng cao ⇒ bước sóng càng ngắn.',['Tính λ','Phổ điện từ']),
T('Photon','Ánh sáng trao đổi năng lượng theo từng lượng tử photon.','E=hf=\\frac{hc}{\\lambda}','J; Hz; m','h là hằng số Planck.','Photon có f lớn hơn thì năng lượng lớn hơn.',['Tính E','Tìm λ/f']),
T('Hiện tượng quang điện ngoài','Photon phải có năng lượng đủ lớn để electron thắng công thoát của kim loại.','hf=A+W_{đ,max};\\quad W_{đ,max}=\\frac12mv_{max}^2','J','f≥f0.','Tăng cường độ không thay thế điều kiện tần số giới hạn.',['Tìm f0','Công thoát','vmax']),
T('Giới hạn quang điện','Tần số nhỏ nhất hoặc bước sóng lớn nhất để xảy ra quang điện phụ thuộc công thoát.','hf_0=A;\\quad \\lambda_0=\\frac{hc}{A}','Hz; m; J','Kim loại có công thoát A.','A lớn ⇒ f0 lớn và λ0 nhỏ.',['Tìm λ0','Tìm A']),
T('Mẫu nguyên tử Bohr – năng lượng','Mức năng lượng nguyên tử được lượng tử hóa; chuyển mức phát/thu photon.','hf=|E_m-E_n|','J','Mô hình Bohr cho nguyên tử hydrogen-like.','Photon phát ra khi electron chuyển từ mức cao xuống mức thấp.',['Tính photon','Chuyển mức']),
T('Phóng xạ – định luật suy giảm','Số hạt chưa phân rã giảm theo thời gian theo quy luật mũ.','N=N_0e^{-\\lambda t}=N_0 2^{-t/T_{1/2}}','N: hạt; λ: s⁻¹','Mỗi hạt phân rã ngẫu nhiên nhưng tổng thể tuân quy luật thống kê.','Sau n chu kỳ bán rã: N=N0/2^n.',['Tính N','Tính t','Bán rã']),
T('Độ phóng xạ','Độ phóng xạ là số phân rã xảy ra trong một đơn vị thời gian.','H=\\lambda N=H_0e^{-\\lambda t}','Bq = s⁻¹','λ không đổi với đồng vị.','H giảm cùng quy luật với N.',['Tính H','Bán rã']),
T('Phản ứng hạt nhân – bảo toàn','Trong phản ứng hạt nhân, các định luật bảo toàn được dùng để tìm đại lượng chưa biết.','\\sum m_{trước}c^2-\\sum m_{sau}c^2=Q','Q: J hoặc MeV','Khối lượng dùng đúng hệ đơn vị.','Q>0: tỏa năng lượng; Q<0: thu năng lượng.',['Tính Q','Năng lượng liên kết']),
T('Hệ thức khối lượng – năng lượng','Khối lượng và năng lượng có quan hệ tương đương.','E=mc^2','J; kg','Tương đối tính.','Khối lượng thiếu hụt nhỏ có thể tương ứng năng lượng rất lớn.',['Tính E','Đổi u↔MeV/c²'])
]};

function renderNav(){ $('#navList').innerHTML=`<button class="nav-item active" data-nav="home">⌂ Tổng quan</button>${grades.map(g=>`<button class="nav-item" data-nav="grade" data-grade="${g.id}">▣ ${g.title}</button>`).join('')}<button class="nav-item" data-nav="practice">✓ Luyện tập</button><button class="nav-item" data-nav="saved">★ Đã lưu</button>`; $$('.nav-item').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='home')show('home');if(b.dataset.nav==='grade')showGrade(b.dataset.grade);if(b.dataset.nav==='practice')show('practice');if(b.dataset.nav==='saved')show('saved');closeMenu()})}
function renderGrades(filter=''){const list=grades.filter(g=>(g.title+g.desc+g.topics.join(' ')).toLowerCase().includes(filter.toLowerCase()));$('#gradeGrid').innerHTML=list.map(g=>`<article class="grade-card" tabindex="0" data-grade="${g.id}"><div class="num">${g.id}</div><h3>${g.title}</h3><p>${g.desc}</p><div class="tags">${g.topics.map(x=>`<span class="tag">${x}</span>`).join('')}</div><strong class="formula-count">${topics[g.id].length} mục công thức</strong></article>`).join('');$$('.grade-card').forEach(c=>{c.onclick=()=>showGrade(c.dataset.grade);c.onkeydown=e=>{if(e.key==='Enter')showGrade(c.dataset.grade)}})}
function show(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id+'View').classList.add('active');window.scrollTo({top:0,behavior:'smooth'});$$('.nav-item').forEach(x=>x.classList.remove('active'));const n=$(`[data-nav="${id==='home'?'home':id}"]`);if(n)n.classList.add('active');if(id==='saved')renderSaved()}
function showGrade(g){show('detail');state.topic=g;const arr=topics[g]||[];const grade=grades.find(x=>x.id==g);$('#detailContent').innerHTML=`<div class="detail-head"><div><span class="eyebrow">${grade.title.toUpperCase()} • ${arr.length} MỤC</span><h1>${grade.title}: FULL CÔNG THỨC</h1><p class="muted">Không chỉ học thuộc: <b>bản chất → công thức → đơn vị → điều kiện → dấu/chiều → đồ thị → dạng bài.</b></p></div><button class="btn btn-primary" data-action="practiceGrade">Luyện phần này</button></div><div class="topic-grid">${arr.map((t,i)=>`<article class="topic-card"><div class="topic-number">${String(i+1).padStart(2,'0')}</div><h3>${t.name}</h3><div class="concept"><b>Bản chất</b><p>${t.essence}</p></div><div class="formula"><small>CÔNG THỨC</small><div>\\(${t.formula}\\)</div></div><div class="note-grid"><div class="mini"><b>Đơn vị</b>${t.units}</div><div class="mini"><b>Điều kiện</b>${t.condition}</div><div class="mini"><b>Nhớ bản chất</b>${t.insight}</div></div>${t.graph?`<div class="graph-box"><div class="graph-title">Đồ thị / quan hệ trực quan</div><canvas id="chart-${g}-${i}" aria-label="Đồ thị minh họa ${t.name}"></canvas></div>`:''}<h4>Dạng bài thường gặp</h4><div class="tags">${t.types.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="exercise"><b>Ví dụ nhanh</b><p>${exampleFor(t.name)}</p></div><button class="btn btn-soft save-btn" data-save="${g}-${i}">${state.saved.has(`${g}-${i}`)?'★ Đã lưu':'☆ Lưu chủ đề'}</button></article>`).join('')}</div>`;MathJax.typesetPromise().then(()=>{});arr.forEach((t,i)=>{if(t.graph)drawTopicChart(`chart-${g}-${i}`,t.graph,t.name)});$$('.save-btn').forEach(b=>b.onclick=()=>toggleSave(b.dataset.save));$('[data-action="practiceGrade"]').onclick=()=>show('practice')}
function exampleFor(n){if(n.includes('Dao động điều hòa'))return 'Cho A=5 cm, f=2 Hz, φ=0. Tính ω, vmax và viết phương trình x(t).';if(n.includes('Sóng cơ'))return 'Sóng có f=20 Hz, λ=0,50 m. Tính tốc độ truyền sóng và độ lệch pha giữa hai điểm cách nhau 0,25 m.';if(n.includes('RLC'))return 'Cho R=30 Ω, ZL=40 Ω, ZC=20 Ω. Tính Z, cosφ và I khi U=120 V.';if(n.includes('Newton'))return 'Vẽ sơ đồ lực → chọn trục → chiếu ΣF=ma → giải phương trình.';if(n.includes('Khí lý tưởng'))return 'Một lượng khí đổi từ (p1,V1,T1) sang (p2,V2,T2). Dùng pV/T=const khi n không đổi.';return 'Xác định đại lượng cần tìm → kiểm tra điều kiện áp dụng → đổi SI → chọn công thức → kiểm tra đơn vị và dấu.'}
function drawTopicChart(id,type,name){const c=document.getElementById(id);if(!c)return;const n=100;const labels=Array.from({length:n+1},(_,i)=>i/n);let data=[];let title='';if(type==='sine'){data=labels.map(x=>Math.cos(2*Math.PI*x));title='sin/cos theo thời gian';}else if(type==='line'){data=labels.map(x=>x);title='Quan hệ tuyến tính';}else if(type==='parabola'){data=labels.map(x=>x*x);title='Quan hệ bậc hai';}else if(type==='hyperbola'){data=labels.map(x=>1/(x*2+0.08));title='Tỉ lệ nghịch';}else if(type==='inverse-square'){data=labels.map(x=>1/Math.pow(x*2+0.2,2));title='1/r²';}else if(type==='circle'){data=labels.map(x=>Math.cos(2*Math.PI*x));title='Chuyển động tròn: hình chiếu cos';}else if(type==='standing'){data=labels.map(x=>Math.sin(4*Math.PI*x));title='Sóng dừng';}else if(type==='pV'){data=labels.map(x=>1/(x+.08));title='Đẳng nhiệt pV=const';}else if(type==='rlc'){data=labels.map(x=>Math.sqrt(1+Math.pow(Math.sin(2*Math.PI*x),2)));title='Độ lớn tổng trở minh họa';}else if(type==='resonance'){data=labels.map(x=>1/(0.08+Math.pow((x-.5)*4,2)));title='Cộng hưởng: I đạt cực đại';}else{data=labels.map(x=>Math.sin(2*Math.PI*x));}
new Chart(c,{type:'line',data:{labels,datasets:[{label:title,data,borderWidth:2,pointRadius:0,tension:.18}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true}},scales:{x:{ticks:{maxTicksLimit:6}},y:{grid:{color:'rgba(148,163,184,.15)'}}}}})}
function renderHomeChart(){const c=$('#heroChart');if(!c)return;if(state.chart)state.chart.destroy();const labels=Array.from({length:101},(_,i)=>(i/20).toFixed(2));state.chart=new Chart(c,{type:'line',data:{labels,datasets:[{data:labels.map(x=>Math.cos(Number(x)*2*Math.PI)),borderWidth:3,pointRadius:0,tension:.25}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{x:{display:false},y:{display:false}}}})}
function toggleSave(id){if(state.saved.has(id))state.saved.delete(id);else state.saved.add(id);persist();showGrade(state.topic||id.split('-')[0]);toast(state.saved.has(id)?'Đã lưu vào bộ nhớ của bạn':'Đã bỏ lưu')}
async function persist(){if(!state.user)return;await setDoc(doc(db,'users',state.user.uid),{saved:[...state.saved],updatedAt:new Date().toISOString()},{merge:true}).catch(()=>{})}
async function loadUserData(){if(!state.user)return;const s=await getDoc(doc(db,'users',state.user.uid)).catch(()=>null);if(s?.exists())state.saved=new Set(s.data().saved||[])}
function renderSaved(){if(!state.saved.size){$('#savedList').innerHTML='<div class="saved-item"><b>Chưa có chủ đề.</b><p class="muted">Mở một lớp → bấm “Lưu chủ đề”.</p></div>';return}$('#savedList').innerHTML=[...state.saved].map(id=>{const [g,i]=id.split('-'),t=(topics[g]||[])[i];return t?`<div class="saved-item"><b>Lớp ${g} · ${t.name}</b><p>${t.essence}</p><button class="btn btn-soft" onclick="window.__openSaved('${g}')">Mở</button></div>`:''}).join('')}
window.__openSaved=g=>showGrade(g);
const questions=[
{q:'Trong dao động điều hòa, tại biên vật có đặc điểm nào?',a:['v=0, |a|max','|v|max, a=0','v và a đều cực đại','x=0'],c:0,e:'Ở biên x=±A nên v=0 và |a|=ω²A.'},
{q:'Nếu tần số dao động tăng 2 lần thì chu kỳ?',a:['Tăng 2 lần','Giảm 2 lần','Không đổi','Tăng 4 lần'],c:1,e:'T=1/f nên f tăng 2 lần thì T giảm 2 lần.'},
{q:'RLC nối tiếp cộng hưởng khi:',a:['R=0','ZL=ZC','ZL=R','ZC=R'],c:1,e:'ZL=ZC làm phần cảm và dung triệt tiêu về pha, Z=R.'},
{q:'Trong khí lý tưởng, ở nhiệt độ không đổi:',a:['pV=const','p/T=const','V/T=const','p+V=const'],c:0,e:'Định luật Boyle: p tỉ lệ nghịch V.'},
{q:'Trong định luật II Newton:',a:['F=mv','ΣF=ma','p=ma','F=mg mọi trường hợp'],c:1,e:'Hợp lực quyết định gia tốc: ΣF⃗=m a⃗.'}
];
function renderQuiz(){const q=questions[Math.floor(Math.random()*questions.length)];$('#quizBox').innerHTML=`<span class="eyebrow">CHECK UNDERSTANDING</span><h2>${q.q}</h2>${q.a.map((x,i)=>`<button class="quiz-option" data-i="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}<p id="quizExplain" class="muted"></p>`;$$('.quiz-option').forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===q.c;$$('.quiz-option').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');$('#quizExplain').textContent=(ok?'✓ Đúng. ':'✗ Chưa đúng. ')+q.e})}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function closeMenu(){$('#sidebar').classList.remove('open');$('#menuBtn').setAttribute('aria-expanded','false')}
$('#menuBtn').onclick=()=>{$('#sidebar').classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',$('#sidebar').classList.contains('open'))};$('#closeMenu').onclick=closeMenu;$('#searchInput').oninput=e=>renderGrades(e.target.value);$('[data-action="start"]').onclick=()=>showGrade('11');$('[data-action="random"]').onclick=()=>showGrade(['9','10','11','12'][Math.floor(Math.random()*4)]);$('[data-action="randomQuestion"]').onclick=renderQuiz;$('[data-action="home"]').onclick=()=>show('home');$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dark',document.body.classList.contains('dark'))};
$('#authBtn').onclick=()=>state.user?signOut(auth):$('#authDialog').showModal();$('#loginBtn').onclick=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('#email').value,$('#password').value);$('#authDialog').close();toast('Đăng nhập thành công')}catch(err){toast(err.code||'Đăng nhập thất bại')}};$('#signupBtn').onclick=async()=>{try{await createUserWithEmailAndPassword(auth,$('#email').value,$('#password').value);$('#authDialog').close();toast('Tạo tài khoản thành công')}catch(err){toast(err.code||'Không tạo được tài khoản')}};
onAuthStateChanged(auth,async u=>{state.user=u;$('#authBtn').textContent=u?'Đăng xuất':'Đăng nhập';await loadUserData();});
renderNav();renderGrades();renderQuiz();renderHomeChart();if(localStorage.getItem('dark')==='true')document.body.classList.add('dark');
